version: '3.7'

services:
  web:
    build: .
    command: >
      sh -c "edge_manage --config deploy/edgemanage/edgemanage.yaml --dnet test &&
             edge_query --config deploy/edgemanage/edgemanage.yaml --dnet test &&
             python manage.py test"
    volumes:
      - .:/usr/src/deflect-core/
    ports:
      - 8000:8000
    env_file:
      - ./core/.env
    depends_on:
      - db
  db:
    image: mysql:5.7.34
    ports:
     - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./deploy/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: deflect-core-ci
      MYSQL_ROOT_PASSWORD: password
