version: '3.7'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/deflect-core/web/static
    ports:
      - 8000
    env_file:
      - ./core/.env
    depends_on:
      - db
  db:
    image: mysql:5.7.34
    ports:
     - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./deploy/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: deflect-core
      MYSQL_ROOT_PASSWORD: password
  nginx:
    build: ./deploy/nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/deflect-core/web/static
    depends_on:
      - web
