# Generated by Django 3.1 on 2020-09-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.website')),
            ],
        ),
    ]
