# Generated by Django 3.1 on 2020-09-24 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_website_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=6)),
                ('hostname', models.CharField(max_length=255)),
                ('value', models.TextField(default='')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('deflect', models.BooleanField(default=False)),
                ('port', models.IntegerField(blank=True, default=None, null=True)),
                ('ttl', models.IntegerField(blank=True, default=3600, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.website')),
            ],
        ),
    ]
