# Generated by Django 3.1 on 2020-09-24 16:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostnames', models.TextField()),
                ('fingerprint', models.CharField(max_length=255)),
                ('has_private', models.BooleanField(blank=True, default=False, null=True)),
                ('issuing_ca', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_expires', models.DateTimeField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='api.website')),
            ],
        ),
    ]
