# Generated by Django 3.1 on 2020-09-25 05:25

from django.db import migrations, models
import django.db.models.deletion
import uuid
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_create_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='YamlDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch_time', models.BigIntegerField()),
                ('prev_epoch_time', models.BigIntegerField()),
                ('diff', yamlfield.fields.YAMLField()),
                ('partition', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
        ),
    ]
