# Generated by Django 3.1 on 2020-09-25 09:27

import api.models.website
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_create_yaml_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='admin_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='ats_purge_secret',
            field=models.CharField(blank=True, default=api.models.website.generate_ats_purge_secret, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='banjax_auth_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiteoption',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.website'),
        ),
    ]
