# Generated by Django 3.1 on 2020-10-08 16:19

import api.models.yaml_diff
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_adjust_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteoption',
            name='data',
            field=models.JSONField(blank=True, null=True),
        )
    ]
