# Generated by Django 3.1 on 2020-10-08 16:37

import api.models.website
import api.models.yaml_diff
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_option_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='awstats_password',
            field=models.CharField(default=api.models.website.generate_awstats_password, max_length=40),
        ),
        migrations.AlterField(
            model_name='yamldiff',
            name='diff',
            field=api.models.yaml_diff.CustomYAMLField(),
        ),
    ]
