# Generated by Django 3.1 on 2020-10-09 08:17

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fix_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteoption',
            name='data',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
