# Generated by Django 3.1 on 2021-04-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dnets', to='api.dnet')),
            ],
        ),
    ]
