version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working_directory: ~/deflect-core
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run: git submodule update --init
      - run:
          name: Install edgemanage
          command: cd edgemanage3 && sudo python setup.py install
      - run:
          name: Init edgemanage
          command: edge_manage --config tests/edgemanage/edgemanage.yaml --dnet test
      - run:
          name: Test edge_query
          command: edge_query --config tests/edgemanage/edgemanage.yaml --dnet test -v
      - python/save-cache
      - run:
          name: Setup SQLite on CI
          command: |
            cp core/.env.ci core/.env
            python manage.py migrate
      - run:
          command: python test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
