version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working_directory: ~/deflect-core
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      # Install named-checkzone
      - run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes bind9utils
      - run: git submodule update --init
      - run:
          name: Install edgemanage
          command: cd edgemanage3 && sudo python setup.py install
      - run:
          name: Init edgemanage
          command: edge_manage --config tests/edgemanage/edgemanage.yaml --dnet test
      - run:
          name: Test edge_query
          command: edge_query --config tests/edgemanage/edgemanage.yaml --dnet test -v
      - run:
          name: Setup SQLite on CI
          command: |
            cp core/.env.ci core/.env
            python manage.py migrate
      - run:
          name: Setup gen_site_config output dir
          command: |
            mkdir /tmp/part1
            mkdir /tmp/part2
      - python/save-cache
      - run:
          name: Test / Coverage Report
          command: |
            pip install coverage
            coverage run --source . --omit='venv/*,edgemanage3/*' manage.py test
            coverage html
      - store_artifacts:
          name: Upload htmlcov to artifacts
          path: htmlcov
          destination: artifact-file
      - store_artifacts:
          name: Upload logs to artifacts
          path: dev/logs
          destination: artifact-file

workflows:
  main:
    jobs:
      - build-and-test
