version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working_directory: ~/deflect-core
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          name: Install deps with apt-get
          command: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes bind9utils
      - run: git submodule update --init
      - run:
          name: Install edgemanage
          command: cd edgemanage3 && sudo python setup.py install
      - run:
          name: Install deflect_next
          command: cd deflect_next_orchestration && pip install .
      - run:
          name: Init edgemanage
          command: edge_manage --config tests/edgemanage/edgemanage.yaml --dnet test
      - run:
          name: Test edge_query
          command: edge_query --config tests/edgemanage/edgemanage.yaml --dnet test -v
      - run:
          name: Setup SQLite on CI
          command: |
            cp core/.env.ci core/.env
            python manage.py migrate
      - run:
          name: Setup gen_site_config output dir
          command: |
            mkdir /tmp/part1
            mkdir /tmp/part2
      - python/save-cache
      - run:
          name: Test / Coverage Report
          command: |
            pip install coverage
            coverage run --source . --omit='venv/*,edgemanage3/*' manage.py test
            coverage html
      - run:
          name: Install deps for api docs
          command: |
            python -m pip install git+https://github.com/jeremy5189/apistar
            pip install uritemplate==3.0.1
      - run:
          name: Generate API Docs
          command: |
            python manage.py generateschema --title 'Deflect Core API Documentation' --format openapi-json > docs/schema.json
            python manage.py docs_proc -i docs/schema.json -o docs/schema-altered.json
            apistar docs --path docs/schema-altered.json --format openapi --theme swaggerui --output-dir docs/api-docs
      - persist_to_workspace:
          root: docs
          paths: api-docs
      - store_artifacts:
          name: Upload API docs to artifacts
          path: docs/api-docs
          destination: api-docs
      - store_artifacts:
          name: Upload htmlcov to artifacts
          path: htmlcov
          destination: coverage-report
      - store_artifacts:
          name: Upload logs to artifacts
          path: dev/logs
          destination: logs
  docs-deploy:
    docker:
    - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@deflect.ca"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] Update docs" --dist docs/api-docs
workflows:
  main:
    jobs:
      - build-and-test
      - docs-deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
