test_domain_root: example.com
docker_host_ip: 0.0.0.0
nameserver_hostname: ns1.example.com
nameserver_ip: 0.0.0.0
edge_ips:
  - 0.0.0.0
subdomains:
  - doh
  - kibana
letsencrypt_email: user@example.com
certbot_flags: ~
certbot_upload_pre_gen_certs: false
ssl_ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA"
auth_server:
  server_log_file: "/var/log/nginx/auth-server-format.log"
  iptables_ban_seconds: 10
  iptables_unbanner_seconds: 5  # how often we check for and remove old bans
  kafka_brokers:
    - "localhost:9092"
  global_decision_lists:
    'challenge':
      - '8.8.8.8'
    'allow':
      - '20.20.20.20'
    'block':
      - '30.40.50.60'
  regexes_with_rates:
    - rule: 'instant block'
      regex: '.*blockme.*'
      interval: 1
      hits_per_interval: 0
      decision: 'block'
    - rule: 'instant challenge'
      regex: '.*challengeme.*'
      interval: 1
      hits_per_interval: 0
      decision: 'challenge'
    - rule: 'unblocking backdoor'
      regex: '.*allowme.*'
      interval: 1
      hits_per_interval: 0
      decision: 'allow'
