certbot_options: "--email user@example.com --server https://127.0.0.1:14000/dir --no-verify-ssl"
controller_domain: example.com  # TODO: Edit
controller_ip: 0.0.0.0  # TODO: Edit
doh_private_port: 8085
kibana_private_port: 5601
ssl_ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA"
edge_ips:
  - 0.0.0.0  # TODO: Edit
  - 1.1.1.1  # TODO: Edit
output_prefix: dev/deflect_next/output  # TODO: Edit
banjax_next:
  server_log_file: "/var/log/banjax-next/banjax-next-format.log"
  iptables_ban_seconds: 10
  iptables_unbanner_seconds: 5  # how often we check for and remove old bans
  kafka_brokers:
    - "localhost:9092"
  global_decision_lists:
    'challenge':
      - '8.8.8.8'
    'allow':
      - '20.20.20.20'
    'iptables_block':
      - '30.40.50.60'
  regexes_with_rates:
    - rule: 'instant block'
      regex: '.*blockme.*'
      interval: 1
      hits_per_interval: 0
      decision: 'nginx_block'
    - rule: 'instant challenge'
      regex: '.*challengeme.*'
      interval: 1
      hits_per_interval: 0
      decision: 'challenge'
    - rule: 'unblocking backdoor'
      regex: '.*allowme.*'
      interval: 1
      hits_per_interval: 0
      decision: 'allow'
